#spring.ai.ollama.base-url=http://localhost:11434
#
#spring.ai.ollama.chat.model=deepseek-r1:1.5b
#
#spring.ai.model.chat=ollama

spring.ai.model.chat=ollama
spring.ai.model.embedding=none
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.image=none
spring.ai.model.moderation=none

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=deepseek-r1:1.5b